=== khaledGamal97/XML-ITI/Lab2/family.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="job">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Engineer"/>
			<xs:enumeration value="Accountant"/>
			<xs:enumeration value="Doctor"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sport">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Football"/>
			<xs:enumeration value="Tennis"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Family">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Grandfather">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="Father">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="Mother"/>
										<xs:element name="Daughter">
											<xs:complexType>
												<xs:attribute name="Age" type="xs:integer" use="required"/>
												<xs:attribute name="Job" type="job" default="Engineer"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Son">
											<xs:complexType>
												<xs:attribute name="Age" type="xs:integer" use="required"/>
												<xs:attribute name="Sport" type="sport" default="Football"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Job" type="job" default="Engineer"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Uncle" maxOccurs="4"/>
							<xs:element name="Aunt" maxOccurs="2">
								<xs:complexType>
									<xs:attribute name="Sons" type="xs:integer" default="1" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== khaledGamal97/XML-ITI/Lab2/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<Family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\ITI-BI-Track\7. XML\Day1\Lab2\family.xsd">
	<Grandfather> Khaled
		<Father Job="Engineer"> Ahmed
			<Mother>
			</Mother>
			<Daughter Age="22" Job="Doctor"/>
			<Son Age="25" Sport="Football"/>
		</Father>
		<Uncle/>
		<Uncle/>
		<Uncle/>
		<Aunt/>
	</Grandfather>
</Family>
